=== DORELAS/XML/DTD/skeme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="wname" type="xs:string"/>
	<xs:element name="wife">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="wname"/>
				<xs:element ref="age"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="husband">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="age"/>
				<xs:element ref="wife"/>
			</xs:sequence>
			<xs:attribute name="employed" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="people">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="husband" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="age" type="xs:string"/>
</xs:schema>

=== DORELAS/XML/DTD/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Mon Apr 22 13:08:10 CEST 2019 -->


<?xml-stylesheet type="text/css" href="index.css" ?>
<!DOCTYPE people SYSTEM "skeme.dtd">


<people  xmlns:vl="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                              xsi:noNamespaceSchemaLocation="skeme.xsd">


<husband employed="yes">

<name>John</name>

<age>35</age>

<wife>

<wname>Sara</wname>

<age>22</age>

</wife>

</husband>



<husband employed="no">

<name >Mark</name>

<age>75</age>

<wife>

<wname>Milena</wname>

<age>59</age>

</wife>

</husband>


</people>
